### ISSUE TITLE
upload arduino nano hex file 

### ISSUE THREAD

**Issue by davidxgames** [dimitris-lagos/PlayStation-to-XBox-controller-adapter#1]
I want to make your project, but I can't generate the file to program my arduino nano. 
can you upload the file? please.

**Comment by dimitris-lagos** [comment]
Unless you know what you are doing do NOT flash your Nano, or you might render your arduino unusable. Also unless you have a spare arduino to use as an ISP programmer, or a proper ISP programmer, you cannot proceed with flashing. Flashing with ISP erases the arduino bootloader. Burning the mcu fuses can make your Nano unusable. You have been warned. Use at your own risk.
You need to burn the fuses as shown in the makefile under ATMega48/88/168(it is the same for 328 too). After that, use avrdude to flash with the -e parameter that erases the whole flash(your Nano won't be recognized by the Arduino IDE anymore).
[main.zip](https://github.com/dimitris-lagos/PlayStation-to-XBox-controller-adapter/files/8181829/main.zip)
