### ISSUE TITLE
Arduino nano with atmega328p

### ISSUE THREAD

**Issue by yakaracolombia** [dimitris-lagos/PlayStation-to-XBox-controller-adapter#4]
hello, your project is amazing and the possibilities are amazing, my question is: can I use an arduino nano clone, how would the process be to burn it with arduino ide software. Thank you in advance and I look forward to your response.

**Comment by davidxgames** [comment]
> hello, your project is amazing and the possibilities are amazing, my question is: can I use an arduino nano clone, how would the process be to burn it with arduino ide software. Thank you in advance and I look forward to your response.

You can't yakara, I also tried it, I consulted a friend who is a programmer and works in a software company, he told me it's impossible because of the programming language used.

Maybe Dimitris sheds more light on this.

**Comment by dimitris-lagos** [comment]
To use the Arduino IDE to program your board, your board needs either to be loaded with the arduino bootloader(which is by default) or have a second arduino to use as a programmer. I'm not sure if the arduino bootloader will conflict with the softresets the VUSB library uses to implement the usb device enumeration at startup. Even if the bootloader doesn't interfere, there is some work to be done on the project's header files in order for the Arduino IDE to compile the code. It's beyond the scope of this repo at this point, as I no longer use the Arduino IDE.
I might give a try porting it to the Arduino IDE at some point if I find some spare time.
