### ISSUE TITLE
Four controllers in one

### ISSUE THREAD

**Issue by OmarPadilla22** [dimitris-lagos/PlayStation-to-XBox-controller-adapter#5]
Hi Dimitris...first thanks so match for this contribution, is really awesome and great job.

In secondly, I have a question for you, is possible use just one arduino to convert more of one controller? 

Regards from México

**Comment by dimitris-lagos** [comment]
Hello Omar,
Thanks for your kind words. I'm afraid the arduino uno is not powerfull enough to handle more than one controller at the same time. To use a single microcontroller for 4 controllers, the microcontroller should also have 4 spi interfaces.
